In [130]:
import numpy as np
import pandas as pd

In [131]:
dt  = pd.read_csv("C:\\Users\\Admin\\Downloads\\pmsm_temperature_data.csv")
dt

ambient   coolant       u_d       u_q  motor_speed    torque  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428 -0.250182   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429 -0.249133   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428 -0.249431   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430 -0.248636   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429 -0.248701   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428 -0.255640   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437 -0.255640   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430 -0.255640   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432 -0.255640   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431 -0.255640   

             i_d       i_q        pm  stator_yoke  stator_tooth  \
0       1.029572 -0.245860 -2.522071    -1.831422     -2.066143   
1       1.029509 -0.245832 -2.522418    -1.830969     -2.064859   
2       1.029448 -0.245818 -2.522673    -1.830400     -2.064073   
3       1.032845 -0.246955 -2.521639    -1.830333     -2.063137   
4       1.031807 -0.246610 -2.521900    -1.830498     -2.062795   
...          ...       ...       ...          ...           ...   
998065  1.029142 -0.245723  0.429853     1.018568      0.836084   
998066  1.029148 -0.245736  0.429751     1.013416      0.834438   
998067  1.029191 -0.245701  0.429439     1.002906      0.833936   
998068  1.029147 -0.245727  0.429558     0.999157      0.830504   
998069  1.029141 -0.245722  0.429166     0.987163      0.828046   

        stator_winding  profile_id  
0            -2.018033           4  
1            -2.017631           4  
2            -2.017343           4  
3            -2.017632           4  
4            -2.018145           4  
...                ...         ...  
998065        0.494725          72  
998066        0.494279          72  
998067        0.492666          72  
998068        0.490581          72  
998069        0.489382          72  

[998070 rows x 13 columns]

In [132]:
dt.isnull().sum()

ambient           0
coolant           0
u_d               0
u_q               0
motor_speed       0
torque            0
i_d               0
i_q               0
pm                0
stator_yoke       0
stator_tooth      0
stator_winding    0
profile_id        0
dtype: int64

In [133]:
dt.columns

Index(['ambient', 'coolant', 'u_d', 'u_q', 'motor_speed', 'torque', 'i_d',
       'i_q', 'pm', 'stator_yoke', 'stator_tooth', 'stator_winding',
       'profile_id'],
      dtype='object')

In [134]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998070 entries, 0 to 998069
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   ambient         998070 non-null  float64
 1   coolant         998070 non-null  float64
 2   u_d             998070 non-null  float64
 3   u_q             998070 non-null  float64
 4   motor_speed     998070 non-null  float64
 5   torque          998070 non-null  float64
 6   i_d             998070 non-null  float64
 7   i_q             998070 non-null  float64
 8   pm              998070 non-null  float64
 9   stator_yoke     998070 non-null  float64
 10  stator_tooth    998070 non-null  float64
 11  stator_winding  998070 non-null  float64
 12  profile_id      998070 non-null  int64  
dtypes: float64(12), int64(1)
memory usage: 99.0 MB


In [135]:
dt.describe().transpose()

count       mean        std       min        25%  \
ambient         998070.0  -0.003905   0.993127 -8.573954  -0.599385   
coolant         998070.0   0.004723   1.002423 -1.429349  -1.037925   
u_d             998070.0   0.004780   0.997878 -1.655373  -0.826359   
u_q             998070.0  -0.005690   1.002330 -1.861463  -0.927390   
motor_speed     998070.0  -0.006336   1.001229 -1.371529  -0.951892   
torque          998070.0  -0.003333   0.997907 -3.345953  -0.266917   
i_d             998070.0   0.006043   0.998994 -3.245874  -0.756296   
i_q             998070.0  -0.003194   0.997912 -3.341639  -0.257269   
pm              998070.0  -0.004396   0.995686 -2.631991  -0.672308   
stator_yoke     998070.0   0.000609   1.001049 -1.834688  -0.747265   
stator_tooth    998070.0  -0.002208   0.999597 -2.066143  -0.761951   
stator_winding  998070.0  -0.003935   0.998343 -2.019973  -0.725622   
profile_id      998070.0  50.732001  22.073125  4.000000  32.000000   

                      50%        75%        max  
ambient          0.266157   0.686675   2.967117  
coolant         -0.177187   0.650709   2.649032  
u_d              0.267542   0.358491   2.274734  
u_q             -0.099818   0.852625   1.793498  
motor_speed     -0.140246   0.853584   2.024164  
torque          -0.187246   0.547171   3.016971  
i_d              0.213935   1.013975   1.060937  
i_q             -0.190076   0.499260   2.914185  
pm               0.094367   0.680691   2.917456  
stator_yoke     -0.057226   0.697344   2.449158  
stator_tooth     0.005085   0.772239   2.326668  
stator_winding   0.006536   0.725660   2.653781  
profile_id      56.000000  68.000000  81.000000

In [136]:
dt.drop(['profile_id'], axis = 1, inplace = True)
dt

ambient   coolant       u_d       u_q  motor_speed    torque  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428 -0.250182   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429 -0.249133   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428 -0.249431   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430 -0.248636   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429 -0.248701   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428 -0.255640   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437 -0.255640   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430 -0.255640   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432 -0.255640   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431 -0.255640   

             i_d       i_q        pm  stator_yoke  stator_tooth  \
0       1.029572 -0.245860 -2.522071    -1.831422     -2.066143   
1       1.029509 -0.245832 -2.522418    -1.830969     -2.064859   
2       1.029448 -0.245818 -2.522673    -1.830400     -2.064073   
3       1.032845 -0.246955 -2.521639    -1.830333     -2.063137   
4       1.031807 -0.246610 -2.521900    -1.830498     -2.062795   
...          ...       ...       ...          ...           ...   
998065  1.029142 -0.245723  0.429853     1.018568      0.836084   
998066  1.029148 -0.245736  0.429751     1.013416      0.834438   
998067  1.029191 -0.245701  0.429439     1.002906      0.833936   
998068  1.029147 -0.245727  0.429558     0.999157      0.830504   
998069  1.029141 -0.245722  0.429166     0.987163      0.828046   

        stator_winding  
0            -2.018033  
1            -2.017631  
2            -2.017343  
3            -2.017632  
4            -2.018145  
...                ...  
998065        0.494725  
998066        0.494279  
998067        0.492666  
998068        0.490581  
998069        0.489382  

[998070 rows x 12 columns]

In [137]:
dt["stator_yoke"].unique()

array([-1.8314217 , -1.8309687 , -1.8304    , ...,  1.0029056 ,
        0.99915737,  0.98716253])

In [138]:
dt["stator_tooth"].unique()

array([-2.0661428, -2.0648587, -2.064073 , ...,  0.8339357,  0.8305043,
        0.8280457])

In [139]:
dt["stator_winding"].unique()

array([-2.0180326 , -2.0176313 , -2.0173435 , ...,  0.49472454,
        0.492666  ,  0.48938242])

In [140]:
y = dt.iloc[:,-4].values
y

array([-2.522071  , -2.5224178 , -2.5226731 , ...,  0.4294391 ,
        0.42955777,  0.4291662 ])

In [141]:
x = dt.iloc[:,0:12]
x

ambient   coolant       u_d       u_q  motor_speed    torque  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428 -0.250182   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429 -0.249133   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428 -0.249431   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430 -0.248636   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429 -0.248701   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428 -0.255640   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437 -0.255640   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430 -0.255640   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432 -0.255640   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431 -0.255640   

             i_d       i_q        pm  stator_yoke  stator_tooth  \
0       1.029572 -0.245860 -2.522071    -1.831422     -2.066143   
1       1.029509 -0.245832 -2.522418    -1.830969     -2.064859   
2       1.029448 -0.245818 -2.522673    -1.830400     -2.064073   
3       1.032845 -0.246955 -2.521639    -1.830333     -2.063137   
4       1.031807 -0.246610 -2.521900    -1.830498     -2.062795   
...          ...       ...       ...          ...           ...   
998065  1.029142 -0.245723  0.429853     1.018568      0.836084   
998066  1.029148 -0.245736  0.429751     1.013416      0.834438   
998067  1.029191 -0.245701  0.429439     1.002906      0.833936   
998068  1.029147 -0.245727  0.429558     0.999157      0.830504   
998069  1.029141 -0.245722  0.429166     0.987163      0.828046   

        stator_winding  
0            -2.018033  
1            -2.017631  
2            -2.017343  
3            -2.017632  
4            -2.018145  
...                ...  
998065        0.494725  
998066        0.494279  
998067        0.492666  
998068        0.490581  
998069        0.489382  

[998070 rows x 12 columns]

In [156]:
 x = dt.drop('pm', axis=1).values

In [157]:
x

array([[-0.75214297, -1.1184461 ,  0.3279352 , ..., -1.8314217 ,
        -2.0661428 , -2.0180326 ],
       [-0.77126324, -1.1170206 ,  0.3296648 , ..., -1.8309687 ,
        -2.0648587 , -2.0176313 ],
       [-0.78289163, -1.1166813 ,  0.3327715 , ..., -1.8304    ,
        -2.064073  , -2.0173435 ],
       ...,
       [-0.0423501 ,  0.30741498,  0.33094567, ...,  1.0029056 ,
         0.8339357 ,  0.492666  ],
       [-0.03943322,  0.3020816 ,  0.33098695, ...,  0.99915737,
         0.8305043 ,  0.490581  ],
       [-0.04380252,  0.3126659 ,  0.33082953, ...,  0.98716253,
         0.8280457 ,  0.48938242]])

In [144]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [145]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

In [154]:
x_train

array([[ 0.69743727, -0.68183644, -1.65129305, ..., -0.13430964,
         0.39947848,  0.95029059],
       [-0.02593661, -0.61630139, -0.25875815, ..., -0.81131947,
        -0.90983582, -1.01228389],
       [-0.6265006 , -1.07176303,  0.2394389 , ..., -1.61423986,
        -1.77644326, -1.75917054],
       ...,
       [ 0.70118743, -0.61049479, -0.43106799, ..., -0.16452387,
         0.1439715 ,  0.33137678],
       [-0.07910976,  1.24970507, -0.82891684, ...,  0.95368731,
         0.77369153,  0.4680983 ],
       [-0.46182774,  2.19366683,  0.35538688, ...,  1.66726449,
         1.095263  ,  0.58576635]])

In [155]:
x_test

array([[-0.59582142, -0.64869085,  0.30960804, ..., -1.34285357,
        -1.60215255, -1.62146935],
       [ 0.16731312,  2.2167357 ,  0.15387034, ...,  1.74269907,
         1.35006875,  1.11046158],
       [ 0.5040572 , -0.82107097, -1.39827181, ..., -0.58044506,
        -0.41391666, -0.22705926],
       ...,
       [ 0.09352315, -1.06165652, -1.03494698, ..., -0.73701969,
        -0.43977795, -0.27760794],
       [-0.0487912 , -0.55212529, -0.46408281, ..., -0.18965371,
         0.01531923,  0.16874607],
       [-0.86044853,  0.83303605, -0.25143777, ...,  0.68346651,
         0.45230768,  0.24491794]])

In [148]:
y_train

array([ 0.2879697 , -0.1868631 , -1.0948853 , ...,  0.21665293,
        0.28074396, -0.21814923])

In [149]:
y_test

array([-1.4435408 ,  0.39803383, -0.32377788, ..., -0.08863531,
       -0.6484208 ,  0.52543944])